[package]
name = "starship-plugin-macros"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
starship-plugin-sdk.workspace = true
trybuild = "1.0.116"

[lints]
workspace = true
