[package]
name = "starship-runtime"
description = "The core runtime for the Starship prompt (Lua config, rendering)"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
dashmap = "6.1.0"
mlua = { version = "0.11", features = ["luau", "serde", "error-send"] }
phf = "0.11"
serde.workspace = true
serde_json.workspace = true
starship-common.workspace = true
starship-plugin-core.workspace = true
tempfile = { workspace = true, optional = true }
tracing.workspace = true
wasmtime.workspace = true
which = "8.0.2"

[features]
testing = ["dep:tempfile"]

[build-dependencies]
phf_codegen = "0.11"
serde_json.workspace = true

[dev-dependencies]
filetime = "0.2.27"
tempfile.workspace = true

[lints]
workspace = true
