[package]
name = "starship-bench"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
anyhow.workspace = true
divan = { version = "4", package = "codspeed-divan-compat" }
starship.workspace = true
starship-common.workspace = true
starship-daemon.workspace = true
starship-runtime = { workspace = true, features = ["testing"] }
tempfile.workspace = true

[[bench]]
name = "starship_bench"
harness = false

[lints]
workspace = true
