name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: moonrepo/setup-rust@v1
        with:
          channel: stable
      - run: cargo test
